### ISSUE TITLE
Need to adjust GenPRES page for screen size.

### ISSUE THREAD

**Issue by halcwb** [halcwb/GenPres2#9]
When opening the GenPres demo page, the patient view doesn't fit on a mobile.

**Comment by MrBliz** [comment]
Can you eleborate? What mobile are you looking at it on, as it looks fine on my iPhone 13 Pro. And it fits on an iPhone SE screen too

Is it vertically or horizontally that it doesn't fit? A screen shot would be great.

**Comment by halcwb** [comment]
It does fit on the iphone initially. But once you select a drug scenario in the GenPRES demo page, the window size changes in the sense that it becomes wider.

To reproduce:
1. Go to http://genpres.nl
2. Go to the Genpres demo page.
3. Select a patient
4. Select a medication, indication and route
